projects/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('mainpage/', include('mainpage.urls')),
    path('page/', include('page.urls')),
    path('homepage/', views.page, name='homepage'),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

projects/mysite/mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.file, name='upload'),
]

projects/mysite/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.page, name='page'),
]

projects/mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
     # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
]

projects/mysite/mainpage/models.py
from django.db import models

# Create your models here.

projects/mysite/mainpage/views.py
from django.shortcuts import render



def index(request): return render(request, 'mainpage.html')

def file(request): return render(request, 'img_upload.html')

projects/mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q

from ..models import Question

def index(request):
    """
    pybo 목록 출력
    """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어

    # 조회
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목검색
            Q(content__icontains=kw) |  # 내용검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이검색
        ).distinct()
        
    # 페이징처리
    paginator = Paginator(question_list, 7)  # 페이지당 7개씩 보여주기
    page_obj = paginator.get_page(page)
    
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)

def detail(request, question_id):
    """
    pybo 내용 출력
    """
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

projects/mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    {% load static %}
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <title>ANA</title>
</head>
<body>
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

projects/mysite/templates/img_upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>ANA</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/img_upload.css' %}">
    <script src="{% static 'camera_item.js' %}"></script>
    <style>
        .intro_bg{
            background-image: url( "{% static 'image/intro2.jpg' %}");
        }
    </style>
    <script type="text/javascript">
           $(document).ready(function(){
                $(".page-link").on('click', function() {
                    $("#page").val($(this).data("page"));
                    $("#searchForm").submit();
                });
            
                $("#btn_search").on('click', function() {
                    $("#kw").val($(".kw").val());
                    $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
                    $("#searchForm").submit();
                });
            });
    </script>
</head>
    
<body>
    <div class="wrap">
        <div class="intro_bg">
             <div class="header" id="link_header">
                <ul class="nav">
                    <li><a class="nav-link_iter" href="{% url 'mainpage:index' %}">ANA</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link_iter" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a></li>
                    {% else %}
                    <li><a class="nav-link_iter" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
                </ul>
                <div class="searchArea">
                    <form>
                        <input type="search" placeholder="Search" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                        <span class="btn1_iter" type="button" id="btn_search">검색</span>
                    </form>
                </div>
        </div>
        <div class="table_main0">
            <div class="table_main1">
                <span class="title_h1">이미지 업로드</span>               
                <form method="POST" action="/profile-upload-single" enctype="multipart/form-data">
                    <div class="main_text0">
                        <div class="img_iter" id="thumbnailImgs"></div>
                        <div class="title">
                            <input type="file" id="upImgFiles" onChange="uploadImgPreview();" accept="image/*" multiple>
                        </div>
                    <div>
                </form>
            </div>
        </div>
    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
</body>
</html>

projects/mysite/templates/mainpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/mainpage.css' %}">
    <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    />
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <title>ANA</title>
    <script type="text/javascript">
        function printTime(){
            var clock = document.getElementById("clock");  //id값인 <span>태그를 변수clock에 저장
            var now = new Date(); //객체 생성
             clock.innerHTML =     //태그내부에 태그 설정s
             /*now.getFullYear() + "/" +
             (now.getMonth()+1) + "/"+
             now.getDate()+ " " + */
             now.getHours()+":"+
             now.getMinutes() + ":" +
             now.getSeconds() +
             (now.getHours() >= 12 ? "PM": "AM");
        
             setTimeout("printTime()", 1000);  //1초마다 printTime()함수 호출
           }
           window.onload = function(){ //html 로딩시 콜백함수 호출
            printTime();
           }

           $(document).ready(function(){
                $(".page-link").on('click', function() {
                    $("#page").val($(this).data("page"));
                    $("#searchForm").submit();
                });
            
                $("#btn_search").on('click', function() {
                    $("#kw").val($(".kw").val());
                    $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
                    $("#searchForm").submit();
                });
            });
    </script>
    <style>
        .intro_bg{
            background-image: url( "{% static 'image/intro2.jpg' %}");
        }
        input[id="menuicon"] {display:none;}
        input[id="menuicon"] + label {display:block;width:44px;height:24px;position:relative;cursor:pointer;}
        input[id="menuicon"] + label span {display:block;position:absolute;width:100%;height:5px;border-radius:30px;background:#000;transition:all .35s;}
        input[id="menuicon"] + label span:nth-child(1) {top:0;}
        input[id="menuicon"] + label span:nth-child(2) {top:50%;transform:translateY(-50%);}
        input[id="menuicon"] + label span:nth-child(3) {bottom:0;}
        input[id="menuicon"]:checked + label {z-index:2;}
        input[id="menuicon"]:checked + label span {background:#fff;}
        input[id="menuicon"]:checked + label span:nth-child(1) {top:50%;transform:translateY(-50%) rotate(45deg);}
        input[id="menuicon"]:checked + label span:nth-child(2) {opacity:0;}
        input[id="menuicon"]:checked + label span:nth-child(3) {bottom:50%;transform:translateY(50%) rotate(-45deg);}
        div[class="sidebar"] {width:300px;height:100%;background:#222;position:fixed;top:0;left:-300px;z-index:1;transition:all .35s;}
        input[id="menuicon"]:checked + label + div {left:0;}
        .center {
            position:relative;
            width: 100px;
            height: 100px;
            top: -607px;
            left: 25px;
        }
    </style>
</head>
<body>
        <div class="wrap">
            <div class="intro_bg">
                <div class="header" id="link_header">
                    <ul class="nav">
                        <li><a href="#link_header">ANA</a></li>
                        <li><a href="{% url 'pybo:index' %}">질문 게시판</a></li>
                        <li><a href="#link_main_text1">채팅방</a></li>
                        <li><a href="">택배 조회</a></li>
                        <li><a href="">날씨 조회</a></li>
                        <li><a href="{% url 'mainpage:upload' %}">이미지 업로드</a></li>
                    </ul>
                    <div class="searchArea">
                        <form>
                            <input type="search" placeholder="Search" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                            <span class="btn1_iter" type="button" id="btn_search">검색</span>
                        </form>
                    </div>
                </div>

                <div class="intro_text">
                    <h1 class="animate__animated animate__backInDown">ANA</h1>
                    <h4 class="animate__animated animate__flash">간단한 질문 게시판과 채팅방 등 여러 기능을 구현한 ANA용 포트폴리오</h4>
                </div>

                <div class="center">
                    <input type="checkbox" id="menuicon">
                    <label for="menuicon">
                        <span></span>
                        <span></span>
                        <span></span>
                    </label>
                    <div class="sidebar">
                        <ul class="nav1">
                            <li><a href="#link_header">ANA</a></li>
                            <li><a href="{% url 'pybo:index' %}">질문 게시판</a></li>
                            <li><a href="#link_main_text1">채팅방</a></li>
                            <li><a href="">택배 조회</a></li>
                            <li><a href="">날씨 조회</a></li>
                            <li><a href="{% url 'mainpage:upload' %}">이미지 업로드</a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <div class="clock_iter">
                <div class="clock_1"></div>
                <div class="clock_2" id="clock"></div>
                <div class="clock_3"></div>
            </div>    
            <div class="main_text0" id="link_main_text0">
                <h1>ABOUT</h1>
                <div class="contents1">질문 게시판과 채팅방 등 여러 기능들을 미리 보기할 수 있는 기능을 지원합니다.</div>
                
                <ul class="icons">
                    <li>
                        <div class="icon_img">
                            <img src="{% static 'image/board.png' %}" width="109.4px" height="109.4px">
                        </div>
                        <div class="contents1_bold">질문 검색(RS)</div>
                        <div class="contents2">
                            사용자가 질문들을 미리 보고 질문을 직접 검색할 수 있습니다.
                        </div>
                        <a href="{% url 'homepage' %}"><div class="more">바로 가기</div></a>
                    </li>
                    <li>
                        <div class="icon_img">
                            <img src="{% static 'image/speak.png' %}" width="109.4px" height="109.4px">
                        </div>
                        <div class="contents1_bold">채팅방</div>
                        <div class="contents2">
                            사용자가 익명으로 다른 사용자와 채팅을 할 수 있습니다.
                        </div>
                        <a href=""><div class="more">바로 가기</div></a>
                    </li>
                    <li>
                        <div class="icon_img">
                            <img src="{% static 'image/courier.png' %}" width="109.4px" height="109.4px">
                        </div>
                        <div class="contents1_bold">택배 조회</div>
                        <div class="contents2">
                            사용자가 직접 택배 조회를 할 수 있습니다.
                        </div>
                        <a href=""><div class="more">바로 가기</div></a>
                    </li>
                    <li>
                        <div class="icon_img">
                            <img src="{% static 'image/weather.png' %}" width="109.4px" height="109.4px">
                        </div>
                        <div class="contents1_bold">날씨 조회</div>
                        <div class="contents2">
                            사용자가 직접 날씨 조회를 할 수 수 있습니다.
                        </div>
                        <a href=""><div class="more">바로 가기</div></a>
                    </li>
                    <li>
                        <div class="icon_img">
                            <img src="{% static 'image/img.png' %}" width="109.4px" height="109.4px">
                        </div>
                        <div class="contents1_bold">이미지 업로드</div>
                        <div class="contents2">
                            사용자가 직접 영상과 이미지를 올릴 수 있습니다.
                        </div>
                        <a href="{% url 'mainpage:upload' %}"><div class="more">바로 가기</div></a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <form id="searchForm" method="get" action="{% url 'index' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
</body>
</html>