projects/mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

projects/mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views
from page import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('mainpage/', include('mainpage.urls')),
    path('page/', include('page.urls')),
    path('homepage/', views.page, name='homepage'),
    path('', base_views.index, name='index'),  # '/' 에 해당되는 path
]

projects/mysite/mainpage/urls.py
from django.urls import path

from . import views

app_name = 'mainpage'

urlpatterns = [
    path('', views.index, name='index'),
    path('upload/', views.file, name='upload'),
]

projects/mysite/page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.page, name='page'),
]

projects/mysite/pybo/urls.py
from django.urls import path

from .views import base_views, question_views, answer_views

app_name = 'pybo'

urlpatterns = [
     # base_views.py
    path('',
         base_views.index, name='index'),
    path('<int:question_id>/',
         base_views.detail, name='detail'),

    # question_views.py
    path('question/create/',
         question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/',
         question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/',
         question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/',
         answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/',
         answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/',
         answer_views.answer_delete, name='answer_delete'),
]

projects/mysite/templates/page/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">
    <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    <title>ANA</title>
    <style>
        .intro_bg{
            background-image: url( "{% static 'image/intro2.jpg' %}");
        }
    </style>
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <script src="{% static 'jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'bootstrap.min.js' %}"></script>
    {% load pybo_filter %}
    <script type='text/javascript'>
        $(document).ready(function(){
            $(".page-link").on('click', function() {
                $("#page").val($(this).data("page"));
                $("#searchForm").submit();
            });
        
            $("#btn_rs").on('click', function() {
                $("#kw").val($(".kw").val());
                $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
                $("#searchForm").submit();
            });
        });
        </script>        
</head>
<body>
    <div class="wrap">
        <div class="intro_bg">
            <div class="header" id="link_header">
                <ul class="nav">
                    <li><a class="nav-link_iter" href="{% url 'mainpage:index' %}">ANA</a></li>
                    {% if user.is_authenticated %}
                    <li><a class="nav-link_iter" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a></li>
                    {% else %}
                    <li><a class="nav-link_iter" href="{% url 'common:login' %}">로그인</a></li>
                    {% endif %}
                </ul>
            </div>
            <div class="table_main0">
                <div class="table_main1">
                <div class="main_text1">
                    <h1>RS</h1>
                    <div class="searchArea_iter">
                        <form>
                            <input type="search" placeholder="Search" class="form-control kw" value="{{ kw|default_if_none:'' }}">
                            <div class="btn_img">
                                <img src="{%static 'img/search.png' %}" type="button" id="btn_rs">
                            </div>
                        </form>
                    </div>
                    </div>
        <div class="main_text0">
        <h1>RS</h1>
        <div class="contents1">RS 웹사이트는 검색바를 활용해서 내가 작성한 내용을 찾아주는 기능을 가지고 있습니다.</div>
        
        <ul class="icons">
            <li>
                <div class="contents2">
                    <table class="table table_iter">
                        <thead>
                            <tr>
                                <th>번호</th>
                                <th>제목</th>
                            </tr>
                        </thead>
                    <tbody>
                    {% if homepage %}
                    {% for question in homepage %}
                    <tr>
                        <td>
                            <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                            {{ homepage.paginator.count|sub:homepage.start_index|sub:forloop.counter0|add:1 }}
                        </td>
                        <td>
                            <a href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                        </td>
                    </tr>
                    {% endfor %}
                    {% else %}
                    <tr>
                        <td colspan="3">질문이 없습니다.</td>
                    </tr>
                        {% endif %}
                        </tbody>
                    </table>
                    <!-- 페이징처리 시작 -->
                    <ul class="pagination justify-content-center">
                        <!-- 이전페이지 -->
                        {% if homepage.has_previous %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ homepage.previous_page_number }}">이전</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                        </li>
                        {% endif %}
                        <!-- 페이지리스트 -->
                        {% for page_number in homepage.paginator.page_range %}
                        {% if page_number >= homepage.number|add:-1 and page_number <= homepage.number|add:1 %}
                            {% if page_number == homepage.number %}
                            <li class="page-item active" aria-current="page">
                                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% else %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                            </li>
                            {% endif %}
                        {% endif %}
                        {% endfor %}
                        <!-- 다음페이지 -->
                        {% if homepage.has_next %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ homepage.next_page_number }}">다음</a>
                        </li>
                        {% else %}
                        <li class="page-item disabled">
                            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
                        </li>
                        {% endif %}
                    </ul>
                    <!-- 페이징처리 끝 -->
                </div>
            </li>
        </ul>
    </div>
    <form id="searchForm" method="get" action="{% url 'homepage' %}">
        <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
        <input type="hidden" id="page" name="page" value="{{ page }}">
    </form>
</div>
</div>
</body>
</html>